import { Flex, Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './AuthProvider'
import './globals.css'
import Sidebar from './Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang='en'>
        <body className={inter.className}>
          <AuthProvider>
            <Theme>
              <Flex>
                  <Sidebar />
                  <main className='py-4 px-6 w-full'>
                    {children}
                  </main>
              </Flex>
            </Theme>
          </AuthProvider>
        </body>
    </html>
  )
}
